---
# tasks file to configure direct-lvm mode

- name: install essential stuff
  become: yes
  yum:  name={{ item }}
        state=latest
  with_items:
    - lvm2
  tags:
    - worker

- name: Create a volume group for docker
  become: yes
  lvg:
    vg: docker
    pvs: /dev/xvdb
    state: present
  tags:
    - worker

- name: Create pool for docker
  become: yes
  lvol:
    vg: docker
    lv: thinpool
    size: 95%VG
    opts: --wipesignatures y
  tags:
    - worker

- name: Create pool for docker meta
  become: yes
  lvol:
    vg: docker
    lv: thinpoolmeta
    size: 1%VG
    opts: --wipesignatures y
  tags:
    - worker

# no ansible core module to do this is available :(
- name: convert pool in thinpool
  become: yes
  command: 'lvconvert -y --zero n -c 512K --thinpool docker/thinpool --poolmetadata docker/thinpoolmeta'
  ignore_errors: yes
  tags:
    - worker

- name: Configure autoextension of thin pools
  become: yes
  copy:
    src: docker-thinpool.profile
    dest: /etc/lvm/profile/docker-thinpool.profile
  tags:
    - worker

- name: Apply your new lvm profile
  become: yes
  command: 'lvchange --metadataprofile docker-thinpool docker/thinpool'
  tags:
    - worker
