---
# tasks file for swap
- name: format swap
  become: yes
  command: "mkswap /dev/xvdc"
  when: ansible_swaptotal_mb < 1
  tags:
    - worker

- name: swapon
  become: yes
  command: "swapon /dev/xvdc"
  when: ansible_swaptotal_mb < 1
  tags:
    - worker

- name: Write swap entry in fstab
  become: yes
  mount: name=none
         src=/dev/xvdc
         fstype=swap
         opts=sw
         passno=0
         dump=0
         state=present
  tags:
    - worker
