---
# tasks file for postgresql

- name: install postgresql
  become: yes
  yum:  name={{ item }}
        state=present
  with_items:
    - postgresql-server
    - postgresql-devel
    - postgresql-contrib
    - python-psycopg2
  tags:
    - install
    - cloud

- name: initialize postgresql db
  become: yes
  command: postgresql-setup initdb
  notify: restart postgresql
  register: psql_result
  args:
    creates: /var/lib/pgsql/initdb.log
  failed_when: >
    psql_result.rc != 0 and ("not empty" not in psql_result.stdout)
  changed_when: "psql_result.rc == 0"
  tags:
    - install

- name: Install custom pg_hba config
  become: yes
  template: src=../templates/pg_hba.conf.j2 dest=/var/lib/pgsql/data/pg_hba.conf owner=postgres group=postgres mode=0600
  tags:
    - install

- name: make sure postgres is started
  become: yes
  service:  name=postgresql
            state=restarted
            enabled=yes
  tags:
    - service

- name: create django db
  become: yes
  postgresql_db: name=djangodb
                 login_user=postgres
  tags:
    - install

- name: add django user
  become: yes
  postgresql_user:  db=djangodb
                    name=django
                    password={{ djangodbpass }}
                    login_user=postgres
  tags:
    - user

- name: grant ALL privs to django user on djangodb
  become: yes
  postgresql_privs: database=djangodb
                    state=present
                    privs=ALL
                    type=database
                    objs=djangodb
                    roles=django
                    grant_option=yes
                    login=postgres
  tags:
    - install
