---
# tasks file for postgresql

- name: Download pgsql repo rpm file
  get_url:
    url: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    dest: /tmp/pgdg-centos96-9.6-3.noarch.rpm

- name: Install pgsql rpm from a local file
  become: yes
  yum:
    name: /tmp/pgdg-centos96-9.6-3.noarch.rpm
    state: present

- name: install postgresql
  become: yes
  yum:
    name:
      - postgresql96-server
      - postgresql96-devel
      - postgresql96-contrib
      - python-psycopg2
    state: present

- name: install pip psycopg2 client
  become: yes
  pip:
    name: psycopg2-binary
    executable: pip2

- name: Add pgsql to $PATH.
  become: yes
  copy:
    dest: /etc/profile.d/pgsql.sh
    content: "PATH=$PATH:/usr/pgsql-9.6/bin"

- name: Source pgsql path
  shell: source /etc/profile.d/pgsql.sh

- name: initialize postgresql db
  become: yes
  command: /usr/pgsql-9.6/bin/postgresql96-setup initdb
  notify: restart postgresql
  register: psql_result
  args:
    creates: /var/lib/pgsql/initdb.log
  failed_when: >
    psql_result.rc != 0 and ("not empty" not in psql_result.stdout)
  changed_when: "psql_result.rc == 0"

- name: Install custom pg_hba config
  become: yes
  become_user: postgres
  template: src=../templates/pg_hba.conf.j2 dest=/var/lib/pgsql/9.6/data/pg_hba.conf owner=postgres group=postgres mode=0600

- name: make sure postgres is started
  become: yes
  service:
    name: postgresql-9.6
    state: restarted
    enabled: yes

- name: create django db
  become: yes
  become_user: postgres
  postgresql_db:
    name: djangodb

- name: add django user
  become: yes
  become_user: postgres
  postgresql_user:
    db: djangodb
    name: django
    password: "{{ djangodbpass }}"

  # This is required for running tests
- name: change django dev user
  become: yes
  become_user: postgres
  postgresql_user:
    db: djangodb
    name: django
    role_attr_flags: "CREATEDB"
  when: ('delft3dgt-dev' in group_names) or ('delft3dgt-test' in group_names) or vagrant

- name: grant ALL privs to django user on djangodb
  become: yes
  become_user: postgres
  postgresql_privs:
    database: djangodb
    state: present
    privs: ALL
    type: database
    objs: djangodb
    roles: django
    grant_option: yes
