---
# tasks file for redis
- name: install redis
  become: yes
  yum: name=redis state=latest
  tags:
    - install

- name: make sure redis is started
  become: yes
  service:  name=redis.service
            state=started
            enabled=yes
  tags:
    - service
