---
# tasks file for nginx
- name: install nginx
  become: yes
  yum:  name={{ item }}
        state=latest
  with_items:
    - nginx

- name: install custom nginx configuration
  become: yes
  template: src=../templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf
            mode=0644
  notify:
    - restart nginx

- name: make sure nginx is started on boot
  become: yes
  service:  name=nginx
            state=started
            enabled=yes
