---
# tasks file for apache
  - name: install apache
    become: yes
    yum:
      name: httpd
      state: latest

  - name: remove old installation
    become: yes
    yum:
      name: mod_wsgi
      state: absent

  - name: Set selinux policy to allow httpd to connect to postgres
    become: yes
    seboolean:
      name: httpd_can_network_connect_db
      state: yes
      persistent: yes
    ignore_errors: yes

#  - name: Set SSL certificate
#    become: yes
#    lineinfile: dest=/etc/httpd/conf.d/ssl.conf
#                regexp=^SSLCertificateFile
#                line="SSLCertificateFile /etc/pki/tls/certs/delft3d.crt"
#    tags:
#      - configuration
#
#  - name: Set SSL key
#    become: yes
#    lineinfile: dest=/etc/httpd/conf.d/ssl.conf
#                regexp=^SSLCertificateKeyFile
#                line="SSLCertificateKeyFile /etc/pki/tls/private/delft3d.key"
#    tags:
#      - configuration

  # Don't use hard redirects for now, doesn't work with proxies
  # - name: Copy apache redirect all :80 to https conf
  #   become: yes
  #   template: src=03_ssl.j2 dest=/etc/httpd/conf.d/00_ssl.conf owner=apache group=apache
  #   tags:
  #     - configuration

  - name: make sure apache is started on boot
    become: yes
    service:
      name: httpd
      state: started
      enabled: yes

