### Playbook responsible for creating k8s cluster + dependencies

- name: Create all AWS resources
  hosts: localhost
  roles:
    - { role: aws_s3 }
    - { role: aws_eks }
    - { role: aws_efs }
    - { role: k8s_argo }
    - { role: k8s_addons }

- name: Install delft3D-GT Django 
  hosts: delft3dgt-dev, delft3dgt-accp, delft3dgt-test, delft3dgt-prod
  gather_facts: yes  # required for datadog
  roles:
    - { role: django_app, tags: 'app' }
    - { role: k8s_connection}
    - { role: cloud_amazon}
    - { role: thredds, tags: 'thredds' }
    - { role: svn_server }
    # ansible-galaxy install Datadog.datadog
    - { role: Datadog.datadog, become: yes }
    - { role: datadog_config }
