### Playbook responsible for creating k8s cluster + dependencies

- name: Create all AWS resources
  hosts: localhost
  roles:
    - { role: aws_s3 }
    - { role: aws_eks }
    - { role: aws_efs }
    - { role: k8s_argo }
    - { role: k8s_addons }

- name: Install delft3D-GT Django 
  hosts: delft3dgt-dev, delft3dgt-test, delft3dgt-accp, delft3dgt-prod, !localhost
  gather_facts: yes  # required for datadog
  roles:
    - { role: django_app, tags: 'app'}
    - { role: thredds, tags: 'thredds'}
    # ansible-galaxy install Datadog.datadog
    - { role: Datadog.datadog, become: yes, tags: 'monitoring'}
    - { role: datadog_config, tags: 'monitoring'}
    - { role: cloud_amazon, tags: 'amazon'}
    - { role: k8s_connection, tags: 'amazon'}

