---
# Global configuration
- name: apply common configuration to all nodes
  hosts: delft3dgt-local, delft3dgt-dev, delft3dgt-test, delft3dgt-accp
  gather_facts: no


# most basic roles should be further down due to uninstallation
  roles:
    - worker_delft3d
    - worker_python2.7
    - django_app
    - svn_server
    - postgresql
    - django
    - celery
    - apache
    - redis
    - docker
    - thredds
    - tomcat
    - vcs