---
- name: add datadog repo
  shell: |
    helm repo add datadog https://helm.datadoghq.com
    
- name: install datadog monitoring
  shell: |
    KUBECONFIG=./dist/{{ aws_project_name }}/kube.conf helm upgrade {{ aws_project_name }}-datadog datadog/datadog \
    --install \
    --namespace kube-system \
    --set awsRegion={{ aws_region }} \
    --set datadog.apiKey={{ datadog_api_key }} \
    --set recreate-pods=true
