---
# handlers file for django_app
  - name: restart apache
    become: yes
    service: name=httpd
             state=restarted

  - name: restart celery worker
    become: yes
    service:  name=celery
              state=restarted

  - name: start celery worker
    become: yes
    service:  name=celery
              state=started

  - name: stop celery worker
    become: yes
    service:  name=celery
              state=stopped

  - name: start celerybeat worker
    become: yes
    service:  name=celerybeat
              state=started

  - name: restart celerybeat worker
    become: yes
    service:  name=celerybeat
              state=restarted
