- name: Install argo namespace
  shell: |
    kubectl create ns argo --kubeconfig ./dist/{{ aws_project_name }}/kube.conf
  register: command_result
  failed_when:
    - command_result.rc != 0
    - "'AlreadyExists' not in command_result.stderr"

- name: Define Argo installation
  template:
    src: argo_install.yml.j2
    dest: ./dist/{{ aws_project_name }}/argo_install.yml

- name: Install argo
  shell: |
    kubectl apply -n argo -f ./dist/{{ aws_project_name }}/argo_install.yml --kubeconfig ./dist/{{ aws_project_name }}/kube.conf

- name: Create role binding
  shell: |
    kubectl create rolebinding default-admin --clusterrole=admin --serviceaccount=default:default --kubeconfig ./dist/{{ aws_project_name }}/kube.conf
  register: command_result
  failed_when:
    - command_result.rc != 0
    - "'AlreadyExists' not in command_result.stderr"
