---
# handlers file for docker

- name: start docker
  become: yes
  service: name=docker state=started enabled=yes
  tags:
    - service

- name: restart docker
  become: yes
  service: name=docker state=restarted
  tags:
    - service