---
# tasks file for thredds

# Register MD5 hash from url
- name: Set MD5 hash of thredds.war
  set_fact:
    md5_value: "{{ item }}"
  with_url: "{{ thredds_md5_url }}"

# Download thredds 4.6.6 over https
- name: download and install thredds
  get_url:
    url: "{{ thredds_url }}"
    dest: /usr/share/tomcat/webapps/thredds.war
    owner: tomcat
    timeout: 300
    checksum: "md5:{{ md5_value }}"
  become: yes
  notify: restart tomcat

- name: make sure tomcat is started
  become: yes
  service:  name=tomcat
            state=started
            enabled=yes

- name: wait until thredds is unpacked in the in webapps thredds dir
  wait_for:
    path: /var/lib/tomcat/webapps/thredds/catalog.xml
  tags:
    - install

- name: copy thredds catalog
  become: yes
  template:
    src: catalog.xml.j2
    dest: /var/lib/tomcat/webapps/thredds/catalog.xml
  notify: restart tomcat

- name: copy thredds threddsConfig
  become: yes
  template:
    src: threddsConfig_deltares.xml.j2
    dest: /var/lib/tomcat/webapps/thredds/threddsConfig.xml
  notify: restart tomcat

- name: copy logo
  become: yes
  copy:
    src: "{{ hostInstitution_logoUrl }}"
    dest: "/var/lib/tomcat/webapps/thredds/{{ hostInstitution_logoUrl }}"
  notify: restart tomcat
