---
# tasks file for celery
  - name: create pid folder
    become: yes
    file:  path=/var/run/celery
           state=directory
           mode=0755
           owner=docker
           group=docker

  - name: create log folder
    become: yes
    file:  path=/var/log/celery
           state=directory
           mode=0755
           owner=docker
           group=docker
