---
# tasks file for celery
- name: create pid folder via /usr/lib/tmpfiles.d
  copy:
    mode: 0755
    force: yes
    content: "d /var/run/celery 0755 django django -"
    dest: /etc/tmpfiles.d/celery.conf
    group: django
    owner: django
  become: yes
  tags:
    - configuration
    - worker

- name: create pid folder
  become: yes
  file:  path=/var/run/celery
         state=directory
         mode=0755
         owner=django
         group=django
         recurse=yes
  tags:
    - install
    - worker

- name: create log folder
  become: yes
  file:  path=/var/log/celery
         state=directory
         mode=0755
         owner=django
         group=django
         recurse=yes
  tags:
    - install
    - worker

# Install logrotate for celery
- name: install celery logrotate config
  become: yes
  template: src=celery dest=/etc/logrotate.d/celery
  tags:
    - configuration
    - worker

# Also used for celerybeat
- name: copy celeryd configuration file
  become: yes
  template: src=celery.service.j2 dest=/etc/systemd/system/celery.service
  tags:
    - configuration
    - worker

- name: copy celeryd file
  become: yes
  template: src=celeryd.sysconfig.j2 dest=/etc/sysconfig/celery
  tags:
    - install
    - worker

- name: reload deamon
  become: yes
  shell: systemctl daemon-reload
  tags:
    - worker

- name: create pid folder via /usr/lib/tmpfiles.d
  copy:
    mode: 0755
    force: yes
    content: "d /var/run/celerybeat 0755 django django -"
    dest: /etc/tmpfiles.d/celerybeat.conf
    group: django
    owner: django
  become: yes
  tags:
    - configuration

- name: create pid folder
  become: yes
  file:  path=/var/run/celerybeat
         state=directory
         mode=0755
         owner=django
         group=django
         recurse=yes
  tags:
    - install

- name: create log folder
  become: yes
  file:  path=/var/log/celerybeat
         state=directory
         mode=0755
         owner=django
         group=django
         recurse=yes
  tags:
    - install

# Install logrotate for celerybeat
- name: install celerybeat logrotate config
  become: yes
  template: src=celerybeat dest=/etc/logrotate.d/celerybeat
  tags:
    - configuration

- name: copy celerybeat configuration file
  become: yes
  template: src=celerybeat.service.j2 dest=/etc/systemd/system/celerybeat.service
  tags:
    - configuration

- name: copy celerybeatd file
  become: yes
  template: src=celerybeatd.sysconfig.j2 dest=/etc/sysconfig/celerybeat
  tags:
    - install
    - worker

- name: reload deamon
  become: yes
  shell: systemctl daemon-reload
  tags:
    - service
    - worker
