---
# tasks file for celery
- name: create pid folder via /usr/lib/tmpfiles.d
  lineinfile: line="d /var/run/celery 0755 docker docker -"
              state=present
              create=yes
              dest=/etc/tmpfiles.d/celery.conf
  become: yes
  tags:
    - configuration
    - worker

- name: create pid folder
  become: yes
  file:  path=/var/run/celery
         state=directory
         mode=0755
         owner=docker
         group=docker
  tags:
    - install
    - worker

- name: create log folder
  become: yes
  file:  path=/var/log/celery
         state=directory
         mode=0755
         owner=docker
         group=docker
  tags:
    - install
    - worker

# Install logrotate for celery
- name: install celery logrotate config
  become: yes
  template: src=celery dest=/etc/logrotate.d/celery
  tags:
    - configuration
    - worker

# Also used for celerybeat
- name: copy celeryd configuration file
  become: yes
  template: src=celery.service.j2 dest=/etc/systemd/system/celery.service
  tags:
    - configuration
    - worker

- name: restart celery every night
  become: yes
  cron: name="Restart celery every night"
        minute="35"
        hour="0"
        user="root"
        job="systemctl restart celery.service"
  when: "'aws-docker-manage' in group_names"
  tags:
    - configuration
    - worker

- name: copy celeryd file
  become: yes
  template: src=celeryd.sysconfig.j2 dest=/etc/sysconfig/celery
  tags:
    - install
    - worker

- name: reload deamon
  become: yes
  shell: systemctl daemon-reload
  tags:
    - worker

# celery beat
- name: create pid folder via /usr/lib/tmpfiles.d
  lineinfile: line="d /var/run/celerybeat 0755 docker docker -"
              state=present
              create=yes
              dest=/etc/tmpfiles.d/celerybeat.conf
  become: yes
  tags:
    - configuration

- name: create pid folder
  become: yes
  file:  path=/var/run/celerybeat
         state=directory
         mode=0755
         owner=docker
         group=docker
  tags:
    - install

- name: create log folder
  become: yes
  file:  path=/var/log/celerybeat
         state=directory
         mode=0755
         owner=docker
         group=docker
  tags:
    - install

# Install logrotate for celerybeat
- name: install celerybeat logrotate config
  become: yes
  template: src=celerybeat dest=/etc/logrotate.d/celerybeat
  tags:
    - configuration

- name: copy celerybeat configuration file
  become: yes
  template: src=celerybeat.service.j2 dest=/etc/systemd/system/celerybeat.service
  tags:
    - configuration

- name: copy celerybeatd file
  become: yes
  template: src=celerybeatd.sysconfig.j2 dest=/etc/sysconfig/celerybeat
  tags:
    - install
    - worker

- name: reload deamon
  become: yes
  shell: systemctl daemon-reload
  tags:
    - service
    - worker
