---
# tasks file for celery
- name: create pid folder via /usr/lib/tmpfiles.d
  copy:
    mode: 0755
    force: yes
    content: "d /var/run/celery 0755 django django -"
    dest: /etc/tmpfiles.d/celery.conf
    group: django
    owner: django
  become: yes

- name: create pid folder
  become: yes
  file:  path=/var/run/celery
         state=directory
         mode=0755
         owner=django
         group=django
         recurse=yes

- name: create log folder
  become: yes
  file:  path=/var/log/celery
         state=directory
         mode=0755
         owner=django
         group=django
         recurse=yes

# Install logrotate for celery
- name: install celery logrotate config
  become: yes
  template: src=celery dest=/etc/logrotate.d/celery

# Also used for celerybeat
- name: copy celeryd configuration file
  become: yes
  template: src=celery.service.j2 dest=/etc/systemd/system/celery.service

- name: restart celery every night
  become: yes
  cron: name="Restart celery every night"
        minute="35"
        hour="0"
        user="root"
        job="systemctl restart celery.service"

- name: restart celerybeat every night
  become: yes
  cron: name="Restart celerybeat every night"
        minute="35"
        hour="0"
        user="root"
        job="systemctl restart celerybeat.service"

- name: copy celeryd file
  become: yes
  template: src=celeryd.sysconfig.j2 dest=/etc/sysconfig/celery

- name: reload deamon
  become: yes
  shell: systemctl daemon-reload

- name: create pid folder via /usr/lib/tmpfiles.d
  copy:
    mode: 0755
    force: yes
    content: "d /var/run/celerybeat 0755 django django -"
    dest: /etc/tmpfiles.d/celerybeat.conf
    group: django
    owner: django
  become: yes

- name: create pid folder
  become: yes
  file:  path=/var/run/celerybeat
         state=directory
         mode=0755
         owner=django
         group=django
         recurse=yes

- name: create log folder
  become: yes
  file:  path=/var/log/celerybeat
         state=directory
         mode=0755
         owner=django
         group=django
         recurse=yes

# Install logrotate for celerybeat
- name: install celerybeat logrotate config
  become: yes
  template: src=celerybeat dest=/etc/logrotate.d/celerybeat

- name: copy celerybeat configuration file
  become: yes
  template: src=celerybeat.service.j2 dest=/etc/systemd/system/celerybeat.service

- name: copy celerybeatd file
  become: yes
  template: src=celerybeatd.sysconfig.j2 dest=/etc/sysconfig/celerybeat

- name: reload deamon
  become: yes
  shell: systemctl daemon-reload
