---
# tasks file for django_app

- name: Add django to redis group
  become: yes
  user: state=present
        name={{ app_user }}
        groups={{ redis_user }}
        append=yes
  tags:
    - user

- name: add django static folder
  become: yes
  file: path={{ django_static }}
        state=directory
        mode=0755
        owner=django
        group=django
  tags:
    - install

- name: check if django git exists
  stat: path={{ django_path }}//{{ django_app }}
  register: django_exist

# Clean install -> create -> start celery
- name: add django project folder
  become: yes
  file: path={{ django_path }}
       state=directory
       mode=0755
       owner=django
       group=django
  when: not django_exist.stat.exists
  tags:
    - install

- name: Setup the django git clean
  become: yes
  become_user: django
  git: repo={{ django_git }}
      version="{{ git_branch }}"
      dest={{ django_path }}
      accept_hostkey=yes
  when: not django_exist.stat.exists
  notify: start celery worker
  tags:
    - git
    - install

# Folder exists + vagrant is false -> overwrite everything -> restart celery
- name: Setup the django git overwrite
  become: yes
  become_user: django
  git: repo={{ django_git }}
      version="{{ git_branch }}"
      dest={{ django_path }}
      accept_hostkey=yes
      force=yes
      update=yes
  when: django_exist.stat.exists and not vagrant
  notify: restart celery worker
  tags:
    - git
    - install

- name: install django
  become: yes
  become_user: django
  pip:  requirements={{ requirements_file }}
        extra_args=--upgrade
        virtualenv={{ django_virtualenv }}
  tags:
    - install

- name: create ui directory
  become: yes
  file: path=/opt/delft3d-gt/delft3d-gt-ui/dist
        state=directory
        mode=0755
        owner=django
        group=django
  when: not vagrant
  tags:
    - install

- name: download frontend development
  get_url: url=http://build.deltares.nl/guestAuth/repository/download/Delft3DSobek_OssDelft3DGt_Ui_BuildDevelop/.lastSuccessful/delft3d-gt-ui.zip dest=/tmp/delft3d-gt-ui.zip
  become: yes
  when: "'delft3dgt-dev' in group_names"
  tags:
    - install

- name: download frontend master
  get_url: url=http://build.deltares.nl/guestAuth/repository/download/Delft3DSobek_OssDelft3DGt_Ui_BuildMaster/.lastSuccessful/delft3d-gt-ui-master-.zip dest=/tmp/delft3d-gt-ui.zip
  become: yes
  when: "'delft3dgt-accp' in group_names"
  tags:
    - install

- name: unzip frontend
  unarchive:  src=/tmp/delft3d-gt-ui.zip
              dest=/opt/delft3d-gt/delft3d-gt-ui/dist
              owner=django
              group=django
              mode=0755
              copy=no
  become: yes
  when: not vagrant
  tags:
    - install

- name: delete frontend zip
  file: path=/tmp/delft3d-gt-ui.zip state=absent
  become: yes

# Folder exists + vagrant is true -> do nothing -> restart celery
- name: restart celery when git exists
  debug: msg='restart celery worker'
  notify: restart celery worker
  changed_when: true  # force handler to run
  when: django_exist.stat.exists and vagrant
  tags:
    - service

# End of conditionals

- name: Install custom provisionedsettings.py to project
  become: yes
  become_user: django
  template: src=../templates/provisionedsettings.py.j2 dest={{ django_path }}/{{ django_app }}/provisionedsettings.py
            mode=0664
  tags:
    - configuration

- name: Install django app requirements
  become: yes
  become_user: django
  pip:  requirements=requirements.txt
        chdir={{ django_path }}
        extra_args=--upgrade
        virtualenv={{ django_virtualenv }}
  tags:
    - install

- name: Install django app requirements
  become: yes
  become_user: django
  pip:  requirements=test_requirements.txt
        chdir={{ django_path }}
        extra_args=--upgrade
        virtualenv={{ django_virtualenv }}
  tags:
    - install

- name: Migrate db
  become: yes
  become_user: django
  shell: "source {{ django_virtualenv }}/bin/activate; python manage.py migrate --noinput chdir={{ django_path }}"
  tags:
    - configuration

- name: Generate static dir
  become: yes
  become_user: django
  shell: "source {{ django_virtualenv }}/bin/activate; python manage.py collectstatic --noinput chdir={{ django_path }}"
  notify: restart apache
  tags:
    - install

- name: Copy software.zip for viewing result data
  copy: src=software.zip dest={{ django_static }} owner=django group=django mode=0775
  become: yes
  become_method: sudo
  tags:
    - install
