init_config:

instances:
 - apache_status_url: http://localhost/server-status?auto
 #  apache_user: example_user # if apache_status_url needs HTTP basic auth
 #  apache_password: example_password
 #  disable_ssl_validation: true # if you need to disable SSL cert validation, i.e. for self-signed certs

logs:
    - type: file
      path: /var/log/httpd/access_log
      source: apache
      sourcecategory: http_web_access
      service: apache

    - type: file
      path: /var/log/httpd/error_log
      source: apache
      sourcecategory: http_web_access
      service: apache
