---
# tasks file for worker_delft3d

- name: create docker directory
  file: path=/data/container/delft3d state=directory recurse=yes owner=docker
  become: yes
  tags:
    - install
    - cloud

- name: copy Dockerfile
  # copy: src=Dockerfile dest=/data/container/delft3d force=yes
  template: src=Dockerfile dest=/data/container/delft3d/Dockerfile force=yes
  become: yes
  become_user: docker
  tags:
    - install
    - cloud

- name: copy delft3d rpm
  copy: src={{ delft3d_path }} dest=/data/container/delft3d force=yes
  become: yes
  become_user: docker
  tags:
    - install
    - cloud

- name: start docker
  service: name=docker state=started
  become: yes
  tags:
    - service
    - cloud

- name: build delft3d docker image
  command: docker build --no-cache -t delft3d /data/container/delft3d
  become: yes
  tags:
    - install
    - cloud

- name: create docker workers directory
  file: path=/data/container/files state=directory recurse=yes owner=django group=docker mode=2775
  become: yes
  tags:
    - install
    - cloud

- name: set permissions on docker workers directory
  file: path=/data/container/files state=touch owner=django group=docker mode=2775
  become: yes
  tags:
    - install
    - cloud

# Use the following command to start the container in the provisioned machine:
# docker run -v /data/container/01_standard:/data delft3d
