---
# tasks file for django
  - name: install pip
    become: yes
    become_method: sudo
    yum:  name={{ item }}
          state=latest
    with_items:
          - python-pip
          - python-devel
          - postgresql-devel
          - gcc
          - make
          - git

  - name: upgrade pip
    become: yes
    pip:  name={{ item }}
          extra_args=--upgrade
    with_items:
          - virtualenv
          - pip

  - name: add django user
    become: yes
    user: name=django
          state=present
          shell=/bin/bash

  - name: add virtualenv folder
    become: yes
    file: path={{ django_virtualenv }}
          state=directory
          mode=0755
          owner=django
          group=django

  - name: Add apache to django group
    become: yes
    user: name=httpd
          groups=django
          append=yes