---
# tasks file for django

- name: remove python2
  become: yes
  yum:  name={{ item }}
        state=absent
  with_items:
    - python-devel
    - python-pip
  tags:
    - worker

- name: install develop tools
  become: yes
  yum:  name={{ item }}
        state=latest
  with_items:
    - python34-devel
    - python34-pip
    - postgresql-devel
    - httpd-devel
    - gcc
    - make
  tags:
    - install

- name: upgrade pip
  become: yes
  pip:  name={{ item }}
        extra_args=--upgrade
        executable=pip3.4
  with_items:
    - virtualenv
    - pip
    - mod_wsgi
  tags:
    - install
    - worker

- name: add django user
  become: yes
  user: name=django
        state=present
        shell=/bin/bash
  tags:
    - user
    - worker

- name: Register user id
  become: yes
  become_user: django
  shell: id -u
  register: django_id

- name: add virtualenv folder
  become: yes
  file: path={{ django_virtualenv }}
        state=directory
        mode=0755
        owner=django
        group=django
  tags:
    - install
    - worker

- name: Add apache to django group
  become: yes
  user: name=httpd
        groups=django
        append=yes
  tags:
    - user

- name: Install wsgi module into apache
  become: yes
  shell: mod_wsgi-express install-module > /etc/httpd/conf.modules.d/02-wsgi.conf
  tags:
    - install

- name: Install wsgi configuration into apache
  become: yes
  template: src=../templates/02_django.j2 dest=/etc/httpd/conf.d/02_django.conf owner=apache group=apache mode=0644
  tags:
    - install

- name: Install custom error pages into apache
  become: yes
  template: src=../templates/03_custom-error-pages.j2 dest=/etc/httpd/conf.d/03_custom-error-pages.conf owner=apache group=apache mode=0644
  tags:
    - install
