---
# tasks file for django

- name: remove python3.4
  become: yes
  yum:
    name:
      - python-devel
      - python34-devel
      - python34-pip
    state: absent

- name: install develop tools
  become: yes
  yum:
    name:
      - python36-devel
      - python36-pip
      - python36-virtualenv
      - postgresql-devel
      - httpd-devel
      - gcc
      - make
    state: latest

- name: upgrade pip
  become: yes
  pip:
    name:
      - virtualenv
      - pip
      - mod_wsgi
    extra_args: --upgrade
    executable: pip3.6

- name: add django user
  become: yes
  user: name=django
        state=present
        shell=/bin/bash

- name: Register user id
  become: yes
  become_user: django
  shell: id -u
  register: django_id

- name: add virtualenv folder
  become: yes
  file: path={{ django_virtualenv }}
        state=directory
        mode=0755
        owner=django
        group=django

- name: Add apache to django group
  become: yes
  user: name=httpd
        groups=django
        append=yes

- name: Install wsgi module into apache
  become: yes
  shell: mod_wsgi-express install-module > /etc/httpd/conf.modules.d/02-wsgi.conf

- name: Install wsgi configuration into apache
  become: yes
  template: src=../templates/02_django.j2 dest=/etc/httpd/conf.d/02_django.conf owner=apache group=apache mode=0644

- name: Install custom error pages into apache
  become: yes
  template: src=../templates/03_custom-error-pages.j2 dest=/etc/httpd/conf.d/03_custom-error-pages.conf owner=apache group=apache mode=0644
