---
# tasks file for django

# Moved from common
- name: add delft3dgt user
  become: yes
  user:
    name: "{{ delft3dgtuser }}"
    state: present

- name: add django project folder
  become: yes
  file:
    path: "{{ project_path }}"
    state: directory
    mode: 0755
    owner: "{{ delft3dgtuser }}"
    group: "{{ delft3dgtuser }}"

- name: set selinux permissive :'(
  become: yes
  selinux:
    policy: targeted
    state: permissive

- name: set hostname
  become: yes
  command: hostnamectl set-hostname {{ inventory_hostname }} --static

- name: install develop tools
  become: yes
  yum:
    name:
      - rh-python38-python-devel
      - rh-python38-python-pip
      - postgresql-devel
      - httpd-devel
      - gcc
      - make
    state: latest

- name: enable python3.8 environment
  become: yes
  lineinfile:
    path: "/etc/profile.d/enablepython38.sh"
    line: source scl_source enable rh-python38
    mode: "755"
    create: yes

- name: upgrade pip
  become: yes
  pip:
    name:
      - virtualenv
      - wheel
      - pip
      - mod_wsgi
    extra_args: --upgrade
    executable: /opt/rh/rh-python38/root/usr/local/bin/pip3.8

- name: add django user
  become: yes
  user:
    name: django
    state: present
    shell: /bin/bash

- name: Register user id
  become: yes
  become_user: django
  shell: id -u
  register: django_id

- name: remove virtualenv folder
  become: yes
  file:
    path: "{{ django_virtualenv }}"
    state: absent

- name: add virtualenv folder
  become: yes
  file:
    path: "{{ django_virtualenv }}"
    state: directory
    mode: 0755
    owner: django
    group: django

- name: add results folder
  become: yes
  file:
    path: "{{ results_folder }}"
    state: directory
    mode: 0755
    owner: django
    group: django

- name: Add apache to django group
  become: yes
  user:
    name: httpd
    groups: django
    append: yes

- name: Install wsgi module into apache
  become: yes
  shell: /opt/rh/rh-python38/root/usr/local/bin/mod_wsgi-express install-module > /etc/httpd/conf.modules.d/02-wsgi.conf

- name: Install wsgi configuration into apache
  become: yes
  template:
    src: ../templates/02_django.j2
    dest: /etc/httpd/conf.d/02_django.conf
    owner: apache
    group: apache
    mode: 0644

- name: Install custom error pages into apache
  become: yes
  template:
    src: ../templates/03_custom-error-pages.j2
    dest: /etc/httpd/conf.d/03_custom-error-pages.conf
    owner: apache
    group: apache
    mode: 0644
