---
# tasks file for tomcat7

- name: install tomcat
  yum: name={{ item }}
  with_items:
    - tomcat
    - tomcat-webapps
  become: yes
  become_method: sudo
  notify: start tomcat

- name: copy tomcat server config
  become: yes
  template:
    src: server.xml.j2
    dest: /etc/tomcat/server.xml
  notify: restart tomcat

- name: set tomcat variables
  become: yes
  template:
    src: setenv.sh.j2
    dest: /usr/share/tomcat/bin/setenv.sh
  notify: restart tomcat


