---
# tasks file for stunnel for redis connection
# for this task to run a certificate and key for the redis server are required.

- name: Install stunnel
  become: yes
  yum:
    name: stunnel
    state: latest
  tags:
    - install

- name: Install systemd file for stunnel
  template:
    src: stunnel.service.j2
    dest: /etc/systemd/system/stunnel.service
    force: yes
  become: yes
  
- name: Copy certificate
  become: yes
  copy:
    src: "{{ redis_crt }}"
    dest: /etc/stunnel/redis.crt

- include: redis-server.yml
  when: "'redis' in group_names or 'delft3dgt-redis' in inventory_hostname"

- include: redis-client.yml
  when: "'redis' not in group_names and 'delft3dgt-redis' not in inventory_hostname"

- name: make sure stunnel is started on boot
  become: yes
  service:  name=stunnel
            state=started
            enabled=yes

