---
# tasks file for common
  - name: install epel repository
    become: yes
    yum: name=epel-release state=latest
    tags:
      - install
      - cloud

  - name: upgrade local environment
    become: yes
    yum:  name=*
          update_cache=yes
          state=latest
    tags:
      - install
      - cloud

  - name: install essential stuff
    become: yes
    yum:  name={{ item }}
          state=latest
    with_items:
      - vim
      - mc
      - mlocate
      - htop
      - lynx
      - nco
      - unzip
      - libselinux-python
    tags:
      - package

  - name: Set timezone to Amsterdam
    become: yes
    file: src=/usr/share/zoneinfo/Europe/Amsterdam dest=/etc/localtime state=link force=yes
    tags:
      - configuration
      - cloud

  - name: add delft3dgt user
    become: yes
    user: name={{ delft3dgtuser }}
          state=present
    tags:
      - user
      - cloud

  - name: add django project folder
    become: yes
    file: path={{ project_path }}
          state=directory
          mode=0755
          owner={{ delft3dgtuser }}
          group={{ delft3dgtuser }}
    tags:
      - install
      - cloud

  - name: set selinux permissive :'(
    become: yes
    selinux: policy=targeted state=permissive
    tags:
      - configuration
      - cloud

  - name: set hostname
    become: yes
    command: hostnamectl set-hostname {{ inventory_hostname }} --static
    tags:
      - configuration
