---
# tasks file for common
- name: install epel repository
  become: yes
  yum:
    name: epel-release
    state: latest

- name: upgrade local environment
  become: yes
  yum:
    name: "*"
    update_cache: yes
    state: latest

- name: install essential stuff
  become: yes
  yum:
    name:
      - vim
      - mc
      - mlocate
      - htop
      - unzip
      - tree
      - python3.8
      - python3-libselinux
    state: latest
    
- name: upgrade pip
  become: yes
  pip:
    name:
      - virtualenv
      - wheel
      - pip
      - selinux
    extra_args: --upgrade
    executable: pip3.8

- name: install ntp client
  become: yes
  yum:
    name: chrony

- name: make sure ntpd is started
  become: yes
  service:  
    name: chronyd.service
    state: started
    enabled: yes

- name: set time to utc
  become: yes
  file:
    src: /usr/share/zoneinfo/UTC
    dest: /etc/localtime
    state: link
    force: yes
