---
# tasks file for common
- name: install epel repository
  become: yes
  yum: name=epel-release state=latest
  tags:
    - install
    - worker

- name: upgrade local environment
  become: yes
  yum:  name=*
        update_cache=yes
        state=latest
  tags:
    - install
    - worker

- name: install essential stuff
  become: yes
  yum:  name={{ item }}
        state=latest
  with_items:
    - vim
    - mc
    - mlocate
    - htop
    - lynx
    - nco
    - unzip
    - libselinux-python
    - python-setuptools  # added for Ansible 2.7
    - tree
  tags:
    - package
    - worker

- name: install ntp client
  become: yes
  yum: name=ntp
  tags:
    - configuration
    - worker

- name: make sure ntpd is started
  become: yes
  service:  name=ntpd.service
            state=started
            enabled=yes
  tags:
    - service
    - worker

- name: set time to utc
  become: yes
  file: src=/usr/share/zoneinfo/UTC dest=/etc/localtime state=link force=yes
  tags:
    - configuration
    - worker

- name: add delft3dgt user
  become: yes
  user: name={{ delft3dgtuser }}
        state=present
  tags:
    - user
    - worker

- name: add django project folder
  become: yes
  file: path={{ project_path }}
        state=directory
        mode=0755
        owner={{ delft3dgtuser }}
        group={{ delft3dgtuser }}
  tags:
    - install
    - worker

- name: set selinux permissive :'(
  become: yes
  selinux: policy=targeted state=permissive
  tags:
    - configuration
    - worker

- name: set hostname
  become: yes
  command: hostnamectl set-hostname {{ inventory_hostname }} --static
  tags:
    - configuration
