---
# tasks file for common
- name: install epel repository
  become: yes
  yum:
    name: epel-release
    state: latest

- name: upgrade local environment
  become: yes
  yum:
    name: "*"
    update_cache: yes
    state: latest

- name: install essential stuff
  become: yes
  yum:
    name:
      - vim
      - mc
      - mlocate
      - htop
      - lynx
      - nco
      - unzip
      - libselinux-python
      - python-setuptools  # added for Ansible 2.7
      - python-pip
      - tree
    state: latest
    
- name: install ntp client
  become: yes
  yum:
    name: ntp

- name: make sure ntpd is started
  become: yes
  service:  
    name: ntpd.service
    state: started
    enabled: yes

- name: set time to utc
  become: yes
  file:
    src: /usr/share/zoneinfo/UTC
    dest: /etc/localtime
    state: link
    force: yes
