---
# tasks file for aws-k8s-deps

# Create A VPC
- name: Create VPC
  register: vpc_data
  ec2_vpc_net:
    name: "{{ project_name }}"
    cidr_block: "{{ vpc_cidr }}"
    dhcp_opts_id: "{{ dhcp_options_id }}"
    region: "{{ aws_region }}"
    state: present

- name: Create internet gateway
  ec2_vpc_igw:
    region: "{{ aws_region }}"
    state: present
    vpc_id: "{{ vpc_data.vpc.id }}"

- name: S3 bucket for KOPS state
  register: s3_kops_data
  s3_bucket:
    name: "{{ project_name }}-kops-state"
    region: "{{ aws_region }}"
    state: present
    tags:
      Name: "{{ project_name }}"

- name: S3 bucket for processing results
  register: s3_results_data
  s3_bucket:
    name: "{{ project_name }}-results"
    region: "{{ aws_region }}"
    state: present
    tags:
      Name: "{{ project_name }}"

- name: render S3 policy document template
  template:
    src: s3-profile.json.j2
    dest: ./dist/s3-profile.json

- name: S3 result bucket IAM user
  register: s3_result_iam_user
  iam:
    access_key_state: create
    iam_type: user
    name: "{{ s3_user_name }}"
    region: "{{ aws_region }}"
    state: present

- name: Write S3 IAM user credentials to file
  template:
    src: aws-credentials.j2
    dest: ./dist/credentials

- name: Copy static AWS config file to dist directory
  copy:
    src: "{{ role_path }}/files/aws-config"
    dest: ./dist/config

- name: Attach S3 user iam policy
  iam_policy:
    iam_type: user
    iam_name: "{{ s3_user_name }}"
    policy_name: result-s3-bucket-access
    policy_document: ./dist/s3-profile.json
    region: "{{ aws_region }}"
    state: present

- name: KOPS IAM User
  register: iam_kops_data
  iam:
    access_key_state: create
    iam_type: user
    name: "{{ kops_user_name }}"
    region: "{{ aws_region }}"
    state: present

- name: KOPS IAM group
  iam_group:
    managed_policy:
      - arn:aws:iam::aws:policy/AmazonEC2FullAccess
      - arn:aws:iam::aws:policy/AmazonRoute53FullAccess
      - arn:aws:iam::aws:policy/AmazonS3FullAccess
      - arn:aws:iam::aws:policy/IAMFullAccess
      - arn:aws:iam::aws:policy/AmazonVPCFullAccess
    name: kops
    state: present
    users:
      - "{{ kops_user_name }}"

- name: SSH keypair for master and nodes
  ec2_key:
    key_material: "{{ lookup('file', './secret/{{ ssh_key_name }}.pub' )}}"
    name: "{{ ssh_key_name }}"
    state: present