---
# tasks file for worker_delft3d

  - name: create docker directory
    file: path=/data/container/python27 state=directory recurse=yes owner=docker
    become: yes

  - name: copy Dockerfile
    copy: src=Dockerfile dest=/data/container/python27 force=yes
    become: yes
    become_method: sudo
    become_user: docker

  - name: copy run.sh
    template: src=run.sh.j2 dest=/data/container/python27/run.sh force=yes
    become: yes
    become_method: sudo
    become_user: docker

  - name: copy monitoring_integrated.py
    copy: src=monitoring_integrated.py dest=/data/container/python27 force=yes
    become: yes
    become_method: sudo
    become_user: docker

  - name: copy watcher.py
    copy: src=watcher.py dest=/data/container/python27 force=yes
    become: yes
    become_method: sudo
    become_user: docker

  - name: start docker
    service: name=docker state=started
    become: yes
    become_method: sudo

  - name: build python docker image
    command: docker build -t python27_container /data/container/python27
    become: yes
    become_method: sudo

  - name: create docker workers directory
    file: path=/data/container/files state=directory recurse=yes owner=django group=django mode=0775
    become: yes
    become_method: sudo


# Use the following command to start the container in the provisioned machine:
# docker run python_container