---
# tasks file for worker_sync_cleanup

- name: create docker directory
  file: path=/data/container/sync_cleanup state=directory recurse=yes owner=docker
  become: yes
  tags:
    - install
    - cloud

- name: copy Dockerfile
  template: src=Dockerfile dest=/data/container/sync_cleanup/Dockerfile force=yes
  become: yes
  become_method: sudo
  become_user: docker
  tags:
    - install
    - cloud

- name: copy run.sh
  template: src=run.sh.j2 dest=/data/container/sync_cleanup/run.sh force=yes
  become: yes
  become_method: sudo
  become_user: docker
  tags:
    - install
    - cloud

- name: copy aws configuration
  template: src=aws_config.j2 dest=/data/container/sync_cleanup/aws_config force=yes
  become: yes
  become_method: sudo
  become_user: docker
  tags:
    - install
    - cloud

- name: copy aws credentials
  template: src=aws_credentials.j2 dest=/data/container/sync_cleanup/aws_credentials force=yes
  become: yes
  become_method: sudo
  become_user: docker
  tags:
    - install
    - cloud

- name: start docker
  service: name=docker state=started
  become: yes
  become_method: sudo
  tags:
    - service

- name: build python docker image
  command: docker build --no-cache -t sync_cleanup_container /data/container/sync_cleanup
  become: yes
  become_method: sudo
  tags:
    - install
    - cloud

- name: remove aws configuration
  file: path=/data/container/sync_cleanup/aws_config state=absent
  become: yes
  become_method: sudo
  become_user: docker
  tags:
    - install
    - cloud

- name: remove aws credentials
  file: path=/data/container/sync_cleanup/aws_credentials state=absent
  become: yes
  become_method: sudo
  become_user: docker
  tags:
    - install
    - cloud

- name: create docker workers directory
  file: path=/data/container/files state=directory recurse=yes owner=django group=docker mode=2775
  become: yes
  become_method: sudo
  tags:
    - install

- name: set permissions on docker workers directory
  file: path=/data/container/files state=touch owner=django group=docker mode=2775
  become: yes
  become_method: sudo
  tags:
    - install
    - cloud

